In [6]:
# Task 1

In [1]:
# Given data
transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]

In [2]:
# a) Filter out invalid transactions (price == 0 or quantity < 0)
valid_transactions = [
    t for t in transactions
    if t["price"] > 0 and t["quantity"] >= 0
]
print("Valid transactions:")
for t in valid_transactions:
    print(t)
print()

Valid transactions:
{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU'}
{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US'}
{'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU'}
{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC'}



In [3]:
# b) For each remaining transaction, compute new field total = price * quantity
for t in valid_transactions:
    t["total"] = t["price"] * t["quantity"]

print("Valid transactions with totals:")
for t in valid_transactions:
    print(t)
print()

Valid transactions with totals:
{'id': 1, 'product': 'Laptop', 'price': 1200, 'quantity': 2, 'region': 'EU', 'total': 2400}
{'id': 4, 'product': 'Monitor', 'price': 350, 'quantity': 3, 'region': 'US', 'total': 1050}
{'id': 5, 'product': 'Laptop', 'price': 1200, 'quantity': 1, 'region': 'EU', 'total': 1200}
{'id': 6, 'product': 'Keyboard', 'price': 75, 'quantity': 10, 'region': 'APAC', 'total': 750}



In [4]:
# c) Group by region and compute total revenue per region
region_revenue = {}
for t in valid_transactions:
    region = t["region"]
    region_revenue[region] = region_revenue.get(region, 0) + t["total"]

print("Total revenue per region:")
for region, revenue in region_revenue.items():
    print(f"{region}: {revenue}")
print()

Total revenue per region:
EU: 3600
US: 1050
APAC: 750



In [5]:
# d) Print the region with the highest total revenue and its value
max_region, max_revenue = max(region_revenue.items(), key=lambda x: x[1])
print(f"The region with the highest total revenue is {max_region} with revenue {max_revenue}.")

The region with the highest total revenue is EU with revenue 3600.


In [7]:
# Task 2

In [8]:
# Given data
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

def summarise_sales(daily_sales):
    print("Input daily sales:", daily_sales)
    
    # Total sales
    total = sum(daily_sales)
    print(f"Total sales: {total}")
    
    # Average sales, rounded to 2 decimals
    average = round(total / len(daily_sales), 2)
    print(f"Average daily sales: {average}")
    
    # Best and worst day indices (1-based)
    best_value = max(daily_sales)
    best_day = daily_sales.index(best_value) + 1
    print(f"Best day value: {best_value} (day index: {best_day})")
    
    worst_value = min(daily_sales)
    worst_day = daily_sales.index(worst_value) + 1
    print(f"Worst day value: {worst_value} (day index: {worst_day})")
    
    # Count of days above average
    above_average_count = sum(1 for x in daily_sales if x > average)
    print(f"Number of days above average: {above_average_count}")
    
    print()  # blank line for readability
    
    return {
        "total": total,
        "average": average,
        "best_day": best_day,
        "worst_day": worst_day,
        "above_average_count": above_average_count,
    }

# Call the function and print the result dictionary
summary = summarise_sales(sales)
print("Summary dictionary:", summary)

Input daily sales: [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]
Total sales: 20510
Average daily sales: 1465.0
Best day value: 2200 (day index: 11)
Worst day value: 870 (day index: 4)
Number of days above average: 7

Summary dictionary: {'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


In [9]:
# Task 3

In [10]:
# Given data
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]

# a) Create passing list (grade >= 50)
passing = []
for student in students:
    if student["grade"] >= 50:
        passing.append(student["name"])
print("a) Passing students:", passing)
print()

# b) Print status messages for each student
print("b) Student status:")
for student in students:
    if student["grade"] >= 80:
        print(f"{student['name']}: Excellent")
    elif student["grade"] >= 50:
        print(f"{student['name']}: Pass")
    else:
        print(f"{student['name']}: Fail")
print()

# c) Count low attendance (< 0.80)
low_attendance_count = 0
for student in students:
    if student["attendance"] < 0.80:
        low_attendance_count += 1
print(f"c) Students with low attendance: {low_attendance_count}")
print()

# d) Find highest grade using loop only (no max())
highest_grade_student = None
highest_grade = -1
for student in students:
    if student["grade"] > highest_grade:
        highest_grade = student["grade"]
        highest_grade_student = student
print(f"d) Highest grade (loop): {highest_grade_student['name']} - {highest_grade_student['grade']}")
print()

# e) Find highest grade using max()
max_student = max(students, key=lambda s: s["grade"])
print(f"e) Highest grade (max()): {max_student['name']} - {max_student['grade']}")


a) Passing students: ['Anna', 'Erik', 'Mia', 'Sara', 'Tom', 'Nina', 'Olli']

b) Student status:
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass

c) Students with low attendance: 4

d) Highest grade (loop): Nina - 95

e) Highest grade (max()): Nina - 95


In [11]:
# Task 4

In [15]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

    # a) Add or update asset
    def add_asset(self, ticker, shares, price_per_share):
        self.holdings[ticker] = {
            "shares": shares, 
            "price_per_share": price_per_share
        }

    # b) Calculate total portfolio value
    def total_value(self):
        total = 0
        for holding in self.holdings.values():
            total += holding["shares"] * holding["price_per_share"]
        return total

    # c) Find ticker with highest value
    def most_valuable(self):
        if not self.holdings:
            return None
        max_ticker = None
        max_value = -1
        for ticker, holding in self.holdings.items():
            value = holding["shares"] * holding["price_per_share"]
            if value > max_value:
                max_value = value
                max_ticker = ticker
        return max_ticker

    # d) Readable string representation
    def __str__(self):
        num_assets = len(self.holdings)
        total_val = self.total_value()
        return f"Portfolio for {self.owner}: {num_assets} assets, total value €{total_val:,.2f}"

# Demonstrate usage
print("=== Portfolio Task Demo ===\n")

# Create portfolio and add assets
p = Portfolio("Pekka")
p.add_asset("AAPL", 100, 150.0)    # Apple
p.add_asset("GOOG", 50, 2800.0)    # Google
p.add_asset("TSLA", 25, 250.0)     # Tesla

# Test all methods
print(p)                           # __str__
print(f"Total value: €{p.total_value():,.2f}")
print(f"Most valuable asset: {p.most_valuable()}")
print()

# Test updating existing asset
p.add_asset("AAPL", 150, 155.0)    # Update Apple shares and price
print(p)
print(f"Updated total value: €{p.total_value():,.2f}")


=== Portfolio Task Demo ===

Portfolio for Pekka: 3 assets, total value €161,250.00
Total value: €161,250.00
Most valuable asset: GOOG

Portfolio for Pekka: 3 assets, total value €169,500.00
Updated total value: €169,500.00


In [16]:
# Task 5

In [19]:
# Import the module
from datetime import datetime

# Given data
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]

# Parse date strings into datetime.date objects
print(f"original data -> parsed data object")
dates = []
for date_str, product in orders:
    date_obj = datetime.strptime(date_str, "%Y-%m-%d").date()
    dates.append(date_obj)
    print(f"{date_str} -> {date_obj} ({product})")

print()

# Find earliest and latest dates
earliest = min(dates)
latest = max(dates)
print(f"Earliest order: {earliest}")
print(f"Latest order: {latest}")

# Calculate days between earliest and latest
days_diff = (latest - earliest).days
print(f"Days between first and last order: {days_diff}")


original data -> parsed data object
2025-01-15 -> 2025-01-15 (Laptop)
2025-01-22 -> 2025-01-22 (Phone)
2025-02-03 -> 2025-02-03 (Laptop)
2025-02-14 -> 2025-02-14 (Tablet)
2025-03-01 -> 2025-03-01 (Phone)
2025-03-10 -> 2025-03-10 (Phone)
2025-03-22 -> 2025-03-22 (Laptop)
2025-04-05 -> 2025-04-05 (Monitor)

Earliest order: 2025-01-15
Latest order: 2025-04-05
Days between first and last order: 80


In [20]:
# Task 6

In [22]:
import numpy as np

# Given revenue data (years x quarters)
revenue = np.array([
    [210, 230, 190, 250],  # 2022
    [220, 260, 200, 270],  # 2023
    [250, 290, 230, 310],  # 2024
])

print("=== Analysis ===\n")
print("Original revenue (thousands €):\n", revenue)
print()

# a) Total annual revenue for each year (row sums)
annual_totals = np.sum(revenue, axis=1)
print("a) Annual totals (2022, 2023, 2024):")
print(annual_totals)
print()

# b) Mean quarterly revenue across all years (column means)
quarterly_means = np.round(np.mean(revenue, axis=0), 1)
print("b) Mean quarterly revenue (Q1, Q2, Q3, Q4):")
print(quarterly_means)
print()

# c) Broadcasting: adjust 2024 row with growth factors
growth_factors = np.array([1.05, 1.03, 1.08, 1.02])
revenue_2024_adjusted = revenue[2] * growth_factors
print("c) 2024 adjusted with growth factors:")
print(revenue_2024_adjusted)
print()

# d) Boolean indexing: quarters > 250k
high_revenue = revenue[revenue > 250]
print("d) Quarters exceeding 250k €:")
print(high_revenue)


=== Analysis ===

Original revenue (thousands €):
 [[210 230 190 250]
 [220 260 200 270]
 [250 290 230 310]]

a) Annual totals (2022, 2023, 2024):
[ 880  950 1080]

b) Mean quarterly revenue (Q1, Q2, Q3, Q4):
[226.7 260.  206.7 276.7]

c) 2024 adjusted with growth factors:
[262.5 298.7 248.4 316.2]

d) Quarters exceeding 250k €:
[260 270 290 310]


In [23]:
# Task 7

In [24]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
}
df = pd.DataFrame(data)

print("=== Analysis ===\n")
print("Original DataFrame:\n", df)
print()

# a) Add salary_per_year_exp column
df['salary_per_year_exp'] = np.round(df['salary'] / df['years_exp']).astype(int)
print("a) With salary_per_year_exp added:\n", df[['employee', 'salary', 'years_exp', 'salary_per_year_exp']])
print()

# b) Top 3 by performance_score (descending)
top3 = df.sort_values('performance_score', ascending=False).head(3)
print("b) Top 3 employees by performance:\n", top3[['employee', 'performance_score']])
print()

# c) Finance employees with performance > 4.0 using .loc
finance_high_perf = df.loc[(df['department'] == 'Finance') & (df['performance_score'] > 4.0)]
print("c) Finance with perf > 4.0:\n", finance_high_perf)
print()

# d) Rename years_exp column
df_renamed = df.rename(columns={'years_exp': 'experience_years'})
print("d) After renaming years_exp:\n", df_renamed[['employee', 'experience_years']])
print()

# e) First 4 employees, salary + performance columns using .iloc
salary_perf_first4 = df.iloc[:4, [2, 4]]  # columns 2=salary, 4=performance_score
print("e) First 4 employees (salary, performance):\n", salary_perf_first4)


=== Analysis ===

Original DataFrame:
   employee department  salary  years_exp  performance_score
0     Anna    Finance    4500          5                4.2
1     Erik  Marketing    4000          3                3.8
2      Mia    Finance    4800          7                4.5
3      Leo         IT    5200         10                4.0
4     Sara  Marketing    3900          2                3.5
5      Tom         IT    5100          8                4.9

a) With salary_per_year_exp added:
   employee  salary  years_exp  salary_per_year_exp
0     Anna    4500          5                  900
1     Erik    4000          3                 1333
2      Mia    4800          7                  686
3      Leo    5200         10                  520
4     Sara    3900          2                 1950
5      Tom    5100          8                  638

b) Top 3 employees by performance:
   employee  performance_score
5      Tom                4.9
2      Mia                4.5
0     Anna          

In [25]:
# Task 8

In [26]:
import numpy as np
import pandas as pd

# Generate the data (exactly as specified)
rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

print("=== Analysis ===\n")

# a) Create DataFrame with date as index
df = pd.DataFrame({
    'visitors': visitors,
    'conversion_rate': conversion_rate,
    'avg_order_value': avg_order_value
}, index=days)

print("a) DataFrame with date index:\n")
print(df.head())
print()

# b) Add conversions and daily_revenue columns
df['conversions'] = np.round(df['visitors'] * df['conversion_rate']).astype(int)
df['daily_revenue'] = df['conversions'] * df['avg_order_value']

print("b) With conversions and daily_revenue added:\n")
print(df[['visitors', 'conversions', 'daily_revenue']].head())
print("\nFull summary statistics:")
print(df[['conversions', 'daily_revenue']].describe())


=== Analysis ===

a) DataFrame with date index:

            visitors  conversion_rate  avg_order_value
2025-01-06       206           0.0645            64.30
2025-01-07       472           0.0578            48.44
2025-01-08       437           0.0756            43.26
2025-01-09       221           0.0339            43.61
2025-01-10       563           0.0679            49.39

b) With conversions and daily_revenue added:

            visitors  conversions  daily_revenue
2025-01-06       206           13         835.90
2025-01-07       472           27        1307.88
2025-01-08       437           33        1427.58
2025-01-09       221            7         305.27
2025-01-10       563           38        1876.82

Full summary statistics:
       conversions  daily_revenue
count    28.000000      28.000000
mean     20.607143     995.193571
std      10.368540     519.977632
min       7.000000     305.270000
25%      13.000000     668.677500
50%      17.500000     778.230000
75%      27.2500